language: php
php:
  - 5.6
  - 5.5

services:
  - memcached

script: phpunit --configuration tests/phpunit.xml

after_success:
  # CREATE GIT TAG
  - ./bin/update-gh-pages.sh
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - echo -n $GIT_TAG > public/version
  - git commit -m "Set build VERSION number" public/version
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --tags --quiet https://$GITHUBKEY@github.com/clickalicious/Memcached.php > /dev/null 2>&1

branches:
  except:
    - /^build-[0-9a-z\-]*/
